-- Insert default materials data for OpCentrix MES
-- Execute after creating the materials table 

INSERT OR IGNORE INTO "Materials" ("MaterialCode", "MaterialName", "MaterialType", "Description", "Density", "MeltingPointC", "IsActive", "CostPerGram", "DefaultLayerThicknessMicrons", "DefaultLaserPowerPercent", "DefaultScanSpeedMmPerSec", "MaterialProperties", "CompatibleMachineTypes", "SafetyNotes", "CreatedDate", "LastModifiedDate", "CreatedBy", "LastModifiedBy") VALUES ('TI64-G5', 'Ti-6Al-4V Grade 5', 'Titanium', 'Aerospace grade titanium alloy with excellent strength-to-weight ratio', 4.43, 1660.0, 1, '0.45', 30.0, 85.0, 1200.0, '{}', 'SLS', 'Handle with care. May cause respiratory irritation if inhaled.', datetime('now'), datetime('now'), 'System', 'System');

INSERT OR IGNORE INTO "Materials" ("MaterialCode", "MaterialName", "MaterialType", "Description", "Density", "MeltingPointC", "IsActive", "CostPerGram", "DefaultLayerThicknessMicrons", "DefaultLaserPowerPercent", "DefaultScanSpeedMmPerSec", "MaterialProperties", "CompatibleMachineTypes", "SafetyNotes", "CreatedDate", "LastModifiedDate", "CreatedBy", "LastModifiedBy") VALUES ('TI64-G23', 'Ti-6Al-4V Grade 23 (ELI)', 'Titanium', 'Extra Low Interstitial grade for medical implants', 4.43, 1660.0, 1, '0.65', 25.0, 80.0, 1100.0, '{}', 'SLS', 'Medical grade material. Handle with care.', datetime('now'), datetime('now'), 'System', 'System');

INSERT OR IGNORE INTO "Materials" ("MaterialCode", "MaterialName", "MaterialType", "Description", "Density", "MeltingPointC", "IsActive", "CostPerGram", "DefaultLayerThicknessMicrons", "DefaultLaserPowerPercent", "DefaultScanSpeedMmPerSec", "MaterialProperties", "CompatibleMachineTypes", "SafetyNotes", "CreatedDate", "LastModifiedDate", "CreatedBy", "LastModifiedBy") VALUES ('IN718', 'Inconel 718', 'Nickel', 'High-temperature nickel-chromium superalloy', 8.19, 1336.0, 1, '0.75', 40.0, 90.0, 1000.0, '{}', 'SLS', 'High-temperature alloy. Use appropriate safety equipment.', datetime('now'), datetime('now'), 'System', 'System');

INSERT OR IGNORE INTO "Materials" ("MaterialCode", "MaterialName", "MaterialType", "Description", "Density", "MeltingPointC", "IsActive", "CostPerGram", "DefaultLayerThicknessMicrons", "DefaultLaserPowerPercent", "DefaultScanSpeedMmPerSec", "MaterialProperties", "CompatibleMachineTypes", "SafetyNotes", "CreatedDate", "LastModifiedDate", "CreatedBy", "LastModifiedBy") VALUES ('SS316L', 'Stainless Steel 316L', 'Steel', 'Austenitic stainless steel with low carbon content', 8.0, 1400.0, 1, '0.15', 30.0, 75.0, 1500.0, '{}', 'SLS', 'General purpose stainless steel. Standard safety precautions apply.', datetime('now'), datetime('now'), 'System', 'System');

INSERT OR IGNORE INTO "Materials" ("MaterialCode", "MaterialName", "MaterialType", "Description", "Density", "MeltingPointC", "IsActive", "CostPerGram", "DefaultLayerThicknessMicrons", "DefaultLaserPowerPercent", "DefaultScanSpeedMmPerSec", "MaterialProperties", "CompatibleMachineTypes", "SafetyNotes", "CreatedDate", "LastModifiedDate", "CreatedBy", "LastModifiedBy") VALUES ('ALSI10MG', 'AlSi10Mg', 'Aluminum', 'Aluminum-silicon alloy for lightweight applications', 2.67, 570.0, 1, '0.25', 30.0, 70.0, 1800.0, '{}', 'SLS', 'Aluminum powder - fire hazard. Keep away from ignition sources.', datetime('now'), datetime('now'), 'System', 'System');