#!/bin/bash

echo "=========================================="
echo "WEEKEND OPERATIONS TEST SCRIPT"
echo "=========================================="
echo ""

echo "Testing weekend operations fix for OpCentrix scheduler..."
echo ""

# Test scenarios
echo "TEST SCENARIOS:"
echo "1. Schedule job for Friday (should work)"
echo "2. Schedule job for Saturday with weekend enabled (should work)"
echo "3. Schedule job for Saturday with weekend disabled (should move to Monday)"
echo "4. Schedule job for Sunday with weekend enabled (should work)"
echo "5. Schedule job for Sunday with weekend disabled (should move to Monday)"
echo ""

echo "To test this fix:"
echo "1. Start the application: dotnet run --project OpCentrix"
echo "2. Log in as admin: admin/admin123"
echo "3. Go to Admin > Scheduler Settings"
echo "4. Enable weekend operations:"
echo "   - Check 'Enable Weekend Operations'"
echo "   - Check 'Saturday Operations'"
echo "   - Check 'Sunday Operations'"
echo "   - Save Settings"
echo "5. Go to Scheduler page"
echo "6. Try to create jobs on Friday, Saturday, Sunday"
echo "7. Verify they schedule correctly"
echo ""

echo "Expected Behavior:"
echo "- With weekend operations ENABLED: Jobs should schedule on weekends"
echo "- With weekend operations DISABLED: Weekend jobs should move to Monday 7 AM"
echo ""

echo "KEY FILES FIXED:"
echo "- OpCentrix/Services/SchedulerSettingsService.cs (NEW)"
echo "- OpCentrix/Services/SchedulerService.cs (UPDATED - weekend logic)"
echo "- OpCentrix/Pages/Admin/SchedulerSettings.cshtml (EXISTS - admin UI)"
echo "- OpCentrix/Program.cs (UPDATED - service registration)"
echo ""

echo "Configuration Details:"
echo "- Default weekend operations: ENABLED (changed from disabled)"
echo "- Saturday operations: ENABLED by default"
echo "- Sunday operations: ENABLED by default"
echo "- Settings are cached for 5 minutes for performance"
echo "- Weekend logic uses SchedulerSettingsService for consistency"
echo ""

echo "TESTING STEPS:"
echo ""
echo "1. Enable Weekend Operations:"
echo "   http://localhost:5000/Admin/SchedulerSettings"
echo ""

echo "2. Test Weekend Job Scheduling:"
echo "   http://localhost:5000/Scheduler"
echo "   - Click on a Saturday time slot"
echo "   - Create a job"
echo "   - Verify it schedules for Saturday (not Monday)"
echo ""

echo "3. Test Weekend Disabled:"
echo "   - Go back to Admin settings"
echo "   - Uncheck 'Enable Weekend Operations'"
echo "   - Try to schedule weekend job"
echo "   - Should automatically move to Monday"
echo ""

echo "4. Check Logs:"
echo "   Look for these log messages:"
echo "   - 'Weekend operations disabled globally'"
echo "   - 'Weekend operation check for [date]'"
echo "   - 'Scheduler settings loaded: EnableWeekendOperations='"
echo ""

echo "DATABASE VERIFICATION:"
echo "You can check the SchedulerSettings table in the SQLite database:"
echo "SELECT * FROM SchedulerSettings;"
echo "Look for:"
echo "- EnableWeekendOperations = 1"
echo "- SaturdayOperations = 1"
echo "- SundayOperations = 1"
echo ""

echo "TROUBLESHOOTING:"
echo "If weekend operations still don't work:"
echo "1. Check the application logs for errors"
echo "2. Verify SchedulerSettings table exists and has data"
echo "3. Restart the application to clear any caches"
echo "4. Test with a simple Saturday morning time (8 AM)"
echo ""

echo "SUCCESS CRITERIA:"
echo "? Jobs schedule on Saturday when weekend operations enabled"
echo "? Jobs schedule on Sunday when weekend operations enabled"
echo "? Jobs move to Monday when weekend operations disabled"
echo "? Admin can toggle weekend settings in real-time"
echo "? Settings persist across application restarts"
echo ""

echo "=========================================="
echo "Test completed. Start the application and verify weekend scheduling works!"
echo "=========================================="