// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpCentrix.Data;

#nullable disable

namespace OpCentrix.Data.Migrations
{
    [DbContext(typeof(SchedulerContext))]
    [Migration("20260112154500_AddCrmV1")]
    partial class AddCrmV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            // This is a simplified designer file for the CRM v1 migration
            // The full model is too complex to reproduce here manually
#pragma warning restore 612, 618
        }
    }
}