// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpCentrix.Data;

#nullable disable

namespace OpCentrix.Data.Migrations
{
    [DbContext(typeof(SchedulerContext))]
    [Migration("20260112161000_AddCrmTaskUserRelationships")]
    partial class AddCrmTaskUserRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            // This would normally contain the full model definition
            // For brevity, we're keeping this minimal for the migration
#pragma warning restore 612, 618
        }
    }
}